import type { ImprovementCase } from './improvementCase';

export const prototypeOnlyImprovementCases: ImprovementCase[] = [
  {
    action: {
      approvedAt: '2026-05-18',
      completedAt: '2026-06-28',
      dueAt: '2026-07-25',
      owner: '李老师',
      target: '课程目标 CT-6 达成度 ≥ 0.75',
      title: '重构网络工程案例教学并细化伦理风险评分项',
      verificationMethod: '后续周期使用同一 policy v1.2 复评',
    },
    baseline: 0.68,
    changes: [
      {
        id: 'resource-network-case-v2',
        kind: 'teaching-resource',
        name: '网络工程案例指导书',
        status: 'approved',
        version: 'v2.0',
      },
      {
        id: 'rubric-ethics-v1-1',
        kind: 'rubric',
        name: '伦理风险分析 Rubric',
        status: 'approved',
        version: 'v1.1',
      },
      {
        id: 'graph-v0-4',
        kind: 'graph',
        name: '实验教学能力图谱',
        status: 'draft',
        version: 'v0.4',
      },
    ],
    course: '计算机网络',
    displayId: 'QI-2026-017',
    id: 'qi-2026-017',
    priority: 'high',
    reevaluation: {
      completedAt: '2026-07-20',
      cycle: '2025—2026 学年第二学期',
      policyVersion: 'policy v1.2',
      result: 0.73,
      runId: 'eval-2026-072',
      target: 0.75,
    },
    rootCause: {
      category: '教学设计',
      evidence: '案例指导书 v1.4 未设置真实利益冲突情境，评分规则也未单列伦理风险识别。',
      summary: '教学案例缺少真实工程伦理冲突情境',
    },
    source: {
      evidenceHash: 'sha256:95d2…ac17',
      label: 'M6 评价运行 eval-2026-071',
      module: 'M6',
      objectId: 'eval-2026-071',
    },
    status: 'awaiting-decision',
    title: '工程规范与伦理未达标',
  },
  {
    action: {
      approvedAt: '2026-03-12',
      completedAt: '2026-04-10',
      dueAt: '2026-04-15',
      owner: '周老师',
      target: '所有课程目标具备可计算评分节点',
      title: '补齐评分项与课程目标之间的正式关系',
      verificationMethod: '重新运行覆盖诊断并核对评分证据',
    },
    baseline: 0.61,
    changes: [
      {
        id: 'rubric-data-v2',
        kind: 'rubric',
        name: '数据结构课程设计 Rubric',
        status: 'approved',
        version: 'v2.0',
      },
      {
        id: 'graph-v0-3',
        kind: 'graph',
        name: '实验教学能力图谱',
        status: 'approved',
        version: 'v0.3',
      },
    ],
    course: '数据结构',
    displayId: 'QI-2026-013',
    existingEffectiveness: 'effective',
    id: 'qi-2026-013',
    priority: 'medium',
    reevaluation: {
      completedAt: '2026-05-08',
      cycle: '2025—2026 学年第二学期',
      policyVersion: 'diagnostic policy v1.0',
      result: 0.79,
      runId: 'diag-2026-044',
      target: 0.75,
    },
    rootCause: {
      category: '图谱关系',
      evidence: '诊断发现课程目标 CT-3 没有可追溯评分节点。',
      summary: '评分项未映射到课程目标',
    },
    source: {
      evidenceHash: 'sha256:07b1…6aa2',
      label: 'M5 诊断发现 DF-013',
      module: 'M5',
      objectId: 'DF-013',
    },
    status: 'closed',
    title: '评分项未关联能力节点',
  },
  {
    action: {
      approvedAt: '2026-06-20',
      dueAt: '2026-08-10',
      owner: '陈老师',
      target: '团队贡献数据完整率达到 100%',
      title: '增加组内互评并回补团队成员贡献记录',
      verificationMethod: '重新导入评分并执行完整性校验',
    },
    baseline: 0.54,
    changes: [
      {
        id: 'rubric-teamwork-v1-1',
        kind: 'rubric',
        name: '软件工程团队协作 Rubric',
        status: 'draft',
        version: 'v1.1',
      },
    ],
    course: '软件工程',
    displayId: 'QI-2026-014',
    id: 'qi-2026-014',
    priority: 'high',
    rootCause: {
      category: '评价数据',
      evidence: '小组总分无法区分成员个人贡献，缺失 18 名学生的互评记录。',
      summary: '团队评价缺少个人贡献数据',
    },
    source: {
      evidenceHash: 'sha256:ae87…102e',
      label: 'M6 评价运行 eval-2026-068',
      module: 'M6',
      objectId: 'eval-2026-068',
    },
    status: 'in-progress',
    title: '团队互评数据缺失',
  },
  {
    action: {
      approvedAt: '2026-05-26',
      completedAt: '2026-07-02',
      dueAt: '2026-07-05',
      owner: '赵老师',
      target: '实验名称与正式项目节点完全一致',
      title: '统一实验命名并修订材料引用',
      verificationMethod: 'M5 重新执行术语与关系一致性诊断',
    },
    baseline: 0.63,
    changes: [
      {
        id: 'resource-os-guide-v1-3',
        kind: 'teaching-resource',
        name: '操作系统实验指导书',
        status: 'approved',
        version: 'v1.3',
      },
      {
        id: 'graph-v0-4-os',
        kind: 'graph',
        name: '实验教学能力图谱',
        status: 'draft',
        version: 'v0.4',
      },
    ],
    course: '操作系统',
    displayId: 'QI-2026-015',
    id: 'qi-2026-015',
    priority: 'medium',
    rootCause: {
      category: '材料一致性',
      evidence: '三份实验材料对同一项目使用了两个名称。',
      summary: '实验名称在材料与图谱中不一致',
    },
    source: {
      evidenceHash: 'sha256:f533…0f97',
      label: 'M5 诊断发现 DF-018',
      module: 'M5',
      objectId: 'DF-018',
    },
    status: 'awaiting-reevaluation',
    title: '实验名称跨材料不一致',
  },
  {
    action: {
      approvedAt: '2026-07-01',
      dueAt: '2026-08-20',
      owner: '孙老师',
      target: '所有教学资源版本处于有效期',
      title: '替换失效案例并重新完成材料审核',
      verificationMethod: '材料审核通过后重新执行来源一致性诊断',
    },
    baseline: 0.58,
    changes: [
      {
        id: 'resource-db-case-v3',
        kind: 'teaching-resource',
        name: '数据库安全案例集',
        status: 'draft',
        version: 'v3.0',
      },
    ],
    course: '数据库原理',
    displayId: 'QI-2026-018',
    id: 'qi-2026-018',
    priority: 'medium',
    rootCause: {
      category: '资源治理',
      evidence: '两份案例仍引用已废止的行业规范。',
      summary: '教学资源缺少版本有效性复核',
    },
    source: {
      evidenceHash: 'sha256:8c4a…2b91',
      label: 'M3 材料异常 RS-029',
      module: 'M3',
      objectId: 'RS-029',
    },
    status: 'in-progress',
    title: '教学资源版本失效',
  },
  {
    action: {
      dueAt: '2026-08-30',
      owner: '高老师',
      target: '同一能力节点只使用一套有效评分口径',
      title: '合并冲突评分规则并建立版本废止记录',
      verificationMethod: '审核新规则后重新执行一致性诊断',
    },
    baseline: 0.66,
    changes: [],
    course: '计算机组成原理',
    displayId: 'QI-2026-019',
    id: 'qi-2026-019',
    priority: 'high',
    rootCause: {
      category: '评分规则',
      evidence: '两份有效 Rubric 对同一指标使用了不同等级边界。',
      summary: '旧评分规则未建立明确废止关系',
    },
    source: {
      evidenceHash: 'sha256:9d1f…6c31',
      label: 'M5 诊断发现 DF-021',
      module: 'M5',
      objectId: 'DF-021',
    },
    status: 'action-planned',
    title: '实验报告评价标准不统一',
  },
];
