import type { UploadedMaterial } from './uploadedMaterial';

// 试点示例数据：学校已上传的教学材料
// 专业方向：电子信息工程(嵌入式方向)，与 prototypeOnlyAbilityGraph 学校节点一致
export const prototypeOnlyUploadedMaterials: UploadedMaterial[] = [
  {
    id: 'UM-001',
    fileName: '电子信息工程培养方案(2024版).pdf',
    fileType: 'pdf',
    category: '培养方案',
    uploadTime: '2025-06-18 09:32',
    uploadedBy: '张教务',
    status: 'extracted',
    fileSize: '2.4 MB',
    fileUrl: '/materials/UM-001.pdf',
    extractedNodeCount: 3,
  },
  {
    id: 'UM-002',
    fileName: '数据结构与算法课程大纲.docx',
    fileType: 'docx',
    category: '课程大纲',
    uploadTime: '2025-06-19 14:05',
    uploadedBy: '李教师',
    status: 'extracted',
    fileSize: '860 KB',
    fileUrl: '/materials/UM-002.docx',
    extractedNodeCount: 4,
  },
  {
    id: 'UM-003',
    fileName: '单片机与嵌入式实验指导书.pdf',
    fileType: 'pdf',
    category: '实验指导书',
    uploadTime: '2025-06-20 10:11',
    uploadedBy: '王实验员',
    status: 'extracting',
    fileSize: '5.1 MB',
    fileUrl: '/materials/UM-003.pdf',
  },
  {
    id: 'UM-004',
    fileName: '嵌入式系统原理期末试卷(2024秋).xlsx',
    fileType: 'xlsx',
    category: '试卷',
    uploadTime: '2025-06-21 16:48',
    uploadedBy: '张教务',
    status: 'pending',
    fileSize: '320 KB',
    fileUrl: '/materials/UM-004.xlsx',
  },
  {
    id: 'UM-005',
    fileName: 'FPGA数字系统设计实验项目清单.docx',
    fileType: 'docx',
    category: '实验指导书',
    uploadTime: '2025-06-22 08:20',
    uploadedBy: '王实验员',
    status: 'failed',
    fileSize: '1.2 MB',
    fileUrl: '/materials/UM-005.docx',
    failureReason: '文档格式损坏，无法解析第 3 节表格',
  },
];
