import type { AbilityGraphEdge } from '../abilityGraph';
import {
  prototypeBaseEdge as baseEdge,
  prototypeDraftEdge as draftEdge,
  prototypeEdge as edge,
} from './prototypeEdgeFactory';
import { prototypeSource as source } from './prototypeSource';

export const prototypeAssessmentEdges: AbilityGraphEdge[] = [
  edge({
    ...baseEdge,
    id: 'edge-exp5-contains-task5',
    relation: 'contains-task',
    sourceId: 'experiment-tree',
    targetId: 'assessment-task-tree-report',
    source: source(
      'edge-exp5-task5',
      'material:ds-lab-guide',
      'material-version:ds-lab-guide:v2',
      '数据结构实验指导书',
      'v2',
      '第 44 页 · 提交要求',
    ),
  }),
  edge({
    ...draftEdge,
    id: 'edge-exp6-contains-task6',
    relation: 'contains-task',
    sourceId: 'experiment-comparison',
    targetId: 'assessment-task-comparison-report',
    source: source(
      'edge-exp6-task6',
      'material:ds-lab-guide',
      'material-version:ds-lab-guide:v2',
      '数据结构实验指导书',
      'v2',
      '第 51 页 · 提交要求',
    ),
  }),
  edge({
    ...baseEdge,
    id: 'edge-task5-contains-correctness',
    relation: 'contains-criterion',
    sourceId: 'assessment-task-tree-report',
    targetId: 'criterion-correctness',
    source: source(
      'edge-task5-correctness',
      'material:ds-rubric',
      'material-version:ds-rubric:v4',
      '数据结构实验评分表',
      'v4',
      '第 2 页 · 评分项 1',
    ),
  }),
  edge({
    ...baseEdge,
    id: 'edge-task5-contains-complexity',
    relation: 'contains-criterion',
    sourceId: 'assessment-task-tree-report',
    targetId: 'criterion-complexity',
    source: source(
      'edge-task5-complexity',
      'material:ds-rubric',
      'material-version:ds-rubric:v4',
      '数据结构实验评分表',
      'v4',
      '第 2 页 · 评分项 2',
    ),
  }),
  edge({
    ...draftEdge,
    id: 'edge-task6-contains-performance',
    relation: 'contains-criterion',
    sourceId: 'assessment-task-comparison-report',
    targetId: 'criterion-performance-argument',
    source: source(
      'edge-task6-performance',
      'material:ds-rubric',
      'material-version:ds-rubric:v4',
      '数据结构实验评分表',
      'v4',
      '第 4 页 · 评分项 1',
    ),
  }),
  edge({
    ...baseEdge,
    id: 'edge-correctness-assesses-design',
    relation: 'assesses',
    sourceId: 'criterion-correctness',
    targetId: 'skill-algorithm-design',
    source: source(
      'edge-correctness-skill-design',
      'material:ds-rubric',
      'material-version:ds-rubric:v4',
      '数据结构实验评分表',
      'v4',
      '第 2 页 · 评分项 1 · 评价语义',
    ),
  }),
  edge({
    ...baseEdge,
    id: 'edge-complexity-assesses-performance',
    relation: 'assesses',
    sourceId: 'criterion-complexity',
    targetId: 'skill-performance-analysis',
    source: source(
      'edge-complexity-skill-performance',
      'material:ds-rubric',
      'material-version:ds-rubric:v4',
      '数据结构实验评分表',
      'v4',
      '第 2 页 · 评分项 2 · 评价语义',
    ),
  }),
  edge({
    ...draftEdge,
    id: 'edge-performance-assesses-ba2',
    relation: 'assesses',
    sourceId: 'criterion-performance-argument',
    targetId: 'ability-problem-analysis',
    source: source(
      'edge-performance-ba2',
      'material:ds-rubric',
      'material-version:ds-rubric:v4',
      '数据结构实验评分表',
      'v4',
      '第 4 页 · 评分项 1 · 评价语义',
    ),
  }),
  edge({
    ...baseEdge,
    id: 'edge-correctness-contributes-co3',
    relation: 'contributes-to',
    sourceId: 'criterion-correctness',
    targetId: 'course-outcome-ds-3',
    source: source(
      'edge-correctness-co3',
      'material:ds-evaluation-plan',
      'material-version:ds-evaluation-plan:v1.2',
      '数据结构课程目标评价说明',
      'v1.2',
      '表 3 · CO-DS-3 输入 1',
    ),
  }),
  edge({
    ...baseEdge,
    id: 'edge-complexity-contributes-co3',
    relation: 'contributes-to',
    sourceId: 'criterion-complexity',
    targetId: 'course-outcome-ds-3',
    source: source(
      'edge-complexity-co3',
      'material:ds-evaluation-plan',
      'material-version:ds-evaluation-plan:v1.2',
      '数据结构课程目标评价说明',
      'v1.2',
      '表 3 · CO-DS-3 输入 2',
    ),
  }),
];

