import type { AbilityGraphNode } from '../abilityGraph';
import { prototypeSource as source } from './prototypeSource';

export const prototypeTeachingNodes: AbilityGraphNode[] = [
  {
    id: 'skill-algorithm-design',
    nodeVersionId: 'node-version:skill-algorithm-design:v1',
    code: 'SK-DS-01',
    name: '算法设计与正确性验证',
    definition: '针对给定约束设计算法，并通过典型和边界用例验证正确性。',
    capability: {
      domain: '算法设计',
      cognitiveLevel: 'analyze',
      observableBehaviors: [
        '识别问题对象与关键约束',
        '用测试证据验证算法正确性',
      ],
    },
    type: 'skill',
    status: 'effective',
    owner: '数据结构课程负责人',
    version: 'v1.0',
    source: source(
      'skill-design-v1',
      'material:capability-dictionary',
      'material-version:capability-dictionary:v1',
      '实验教学能力词典',
      'v1',
      '技能 SK-DS-01',
    ),
  },
  {
    id: 'skill-performance-analysis',
    nodeVersionId: 'node-version:skill-performance-analysis:v1',
    code: 'SK-DS-02',
    name: '算法性能分析与论证',
    definition: '分析算法复杂度，设计性能实验，并依据数据说明结论边界。',
    capability: {
      domain: '算法性能分析',
      cognitiveLevel: 'evaluate',
      observableBehaviors: [
        '建立对象、约束与性能之间的关系',
        '用工程语言形成可验证的问题表达',
      ],
    },
    type: 'skill',
    status: 'effective',
    owner: '数据结构课程负责人',
    version: 'v1.0',
    source: source(
      'skill-performance-v1',
      'material:capability-dictionary',
      'material-version:capability-dictionary:v1',
      '实验教学能力词典',
      'v1',
      '技能 SK-DS-02',
    ),
  },
  {
    id: 'knowledge-tree-traversal',
    nodeVersionId: 'node-version:knowledge-tree-traversal:v1',
    code: 'KN-DS-05',
    name: '树与遍历',
    definition: '树结构、递归与非递归遍历的基本概念、性质和实现原理。',
    type: 'knowledge',
    status: 'effective',
    owner: '数据结构课程负责人',
    version: 'v1.0',
    source: source(
      'knowledge-tree-v1',
      'material:ds-syllabus',
      'material-version:ds-syllabus:v3',
      '《数据结构》课程教学大纲',
      'v3',
      '第 9 页 · 树与二叉树',
    ),
  },
  {
    id: 'knowledge-complexity',
    nodeVersionId: 'node-version:knowledge-complexity:v1',
    code: 'KN-DS-06',
    name: '算法复杂度',
    definition: '时间复杂度、空间复杂度、渐进分析及主要影响因素。',
    type: 'knowledge',
    status: 'effective',
    owner: '数据结构课程负责人',
    version: 'v1.0',
    source: source(
      'knowledge-complexity-v1',
      'material:ds-syllabus',
      'material-version:ds-syllabus:v3',
      '《数据结构》课程教学大纲',
      'v3',
      '第 4 页 · 算法分析基础',
    ),
  },
  {
    id: 'experiment-tree',
    nodeVersionId: 'node-version:experiment-tree:v2',
    code: 'EXP-DS-05',
    name: '二叉树遍历与查找',
    definition: '完成递归与非递归遍历、查找及结果验证。',
    type: 'experiment',
    status: 'effective',
    owner: '数据结构实验教师',
    version: 'v2.0',
    source: source(
      'experiment-tree-v2',
      'material:ds-lab-guide',
      'material-version:ds-lab-guide:v2',
      '数据结构实验指导书',
      'v2',
      '第 41 页 · 实验五',
    ),
  },
  {
    id: 'experiment-comparison',
    nodeVersionId: 'node-version:experiment-comparison:v1.1',
    code: 'EXP-DS-06',
    name: '算法性能比较',
    definition: '设计测试集，比较不同数据规模下的算法性能与适用边界。',
    type: 'experiment',
    status: 'draft',
    owner: '数据结构实验教师',
    version: 'v1.1',
    source: source(
      'experiment-comparison-v1.1',
      'material:ds-lab-guide',
      'material-version:ds-lab-guide:v2',
      '数据结构实验指导书',
      'v2',
      '第 48 页 · 实验六',
    ),
  },
  {
    id: 'resource-performance-notebook',
    nodeVersionId:
      'teaching-resource-version:resource-performance-notebook:v1.0',
    code: 'RES-DS-03',
    name: '算法性能测试 Notebook',
    definition: '提供固定随机种子、数据规模梯度、计时和可视化脚手架。',
    type: 'teaching-resource',
    status: 'effective',
    owner: '数据结构实验教师',
    version: 'v1.0',
    source: source(
      'resource-performance-v1',
      'material:ds-resource-catalog',
      'material-version:ds-resource-catalog:v1',
      '数据结构实验教学资源目录',
      'v1',
      '资源 RES-DS-03',
    ),
  },
  {
    id: 'assessment-task-tree-report',
    nodeVersionId: 'node-version:assessment-task-tree-report:v4',
    code: 'AT-DS-05',
    name: '树结构实验报告与代码',
    definition: '提交源代码、测试记录、复杂度分析和实验报告。',
    type: 'assessment-task',
    status: 'effective',
    owner: '数据结构课程负责人',
    version: 'v4.0',
    source: source(
      'task-tree-v4',
      'material:ds-rubric',
      'material-version:ds-rubric:v4',
      '数据结构实验评分表',
      'v4',
      '第 2 页 · 实验五评分结构',
    ),
  },
  {
    id: 'assessment-task-comparison-report',
    nodeVersionId: 'node-version:assessment-task-comparison-report:v2',
    code: 'AT-DS-06',
    name: '算法性能比较报告',
    definition: '提交测试方案、性能数据、图表和结论适用范围。',
    type: 'assessment-task',
    status: 'draft',
    owner: '数据结构课程负责人',
    version: 'v2.0',
    source: source(
      'task-comparison-v2',
      'material:ds-rubric',
      'material-version:ds-rubric:v4',
      '数据结构实验评分表',
      'v4',
      '第 4 页 · 实验六评分结构',
    ),
  },
  {
    id: 'criterion-correctness',
    nodeVersionId: 'node-version:criterion-correctness:v4',
    code: 'RC-DS-11',
    name: '算法正确性',
    definition: '实现满足任务要求，并能通过典型与边界测试。',
    type: 'rubric-criterion',
    status: 'effective',
    owner: '数据结构课程负责人',
    version: 'v4.0',
    source: source(
      'criterion-correctness-v4',
      'material:ds-rubric',
      'material-version:ds-rubric:v4',
      '数据结构实验评分表',
      'v4',
      '第 2 页 · 评分项 1',
    ),
  },
  {
    id: 'criterion-complexity',
    nodeVersionId: 'node-version:criterion-complexity:v4',
    code: 'RC-DS-12',
    name: '复杂度分析',
    definition: '能够说明算法的时间、空间复杂度及主要影响因素。',
    type: 'rubric-criterion',
    status: 'effective',
    owner: '数据结构课程负责人',
    version: 'v4.0',
    source: source(
      'criterion-complexity-v4',
      'material:ds-rubric',
      'material-version:ds-rubric:v4',
      '数据结构实验评分表',
      'v4',
      '第 2 页 · 评分项 2',
    ),
  },
  {
    id: 'criterion-performance-argument',
    nodeVersionId: 'node-version:criterion-performance-argument:v4',
    code: 'RC-DS-13',
    name: '性能比较论证',
    definition: '测试设计合理，数据充分，结论与证据一致并说明适用边界。',
    type: 'rubric-criterion',
    status: 'draft',
    owner: '数据结构课程负责人',
    version: 'v4.0',
    source: source(
      'criterion-performance-v4',
      'material:ds-rubric',
      'material-version:ds-rubric:v4',
      '数据结构实验评分表',
      'v4',
      '第 4 页 · 评分项 1',
    ),
  },
];

