import type { AbilityGraphEdge } from '../abilityGraph';
import {
  prototypeBaseEdge as baseEdge,
  prototypeDraftEdge as draftEdge,
  prototypeEdge as edge,
} from './prototypeEdgeFactory';
import { prototypeSource as source } from './prototypeSource';

export const prototypeTeachingEdges: AbilityGraphEdge[] = [
  edge({
    ...baseEdge,
    id: 'edge-exp5-contributes-co3',
    relation: 'contributes-to',
    sourceId: 'experiment-tree',
    targetId: 'course-outcome-ds-3',
    source: source(
      'edge-exp5-co3',
      'material:ds-lab-guide',
      'material-version:ds-lab-guide:v2',
      '数据结构实验指导书',
      'v2',
      '第 41 页 · 实验目标',
    ),
  }),
  edge({
    ...draftEdge,
    id: 'edge-exp6-contributes-co4',
    relation: 'contributes-to',
    sourceId: 'experiment-comparison',
    targetId: 'course-outcome-ds-4',
    source: source(
      'edge-exp6-co4',
      'material:ds-lab-guide',
      'material-version:ds-lab-guide:v2',
      '数据结构实验指导书',
      'v2',
      '第 48 页 · 实验目标',
    ),
  }),
  edge({
    ...baseEdge,
    id: 'edge-exp5-cultivates-ba2',
    relation: 'cultivates',
    sourceId: 'experiment-tree',
    targetId: 'ability-problem-analysis',
    source: source(
      'edge-exp5-ba2',
      'material:ds-lab-guide',
      'material-version:ds-lab-guide:v2',
      '数据结构实验指导书',
      'v2',
      '第 41 页 · 能力目标',
    ),
  }),
  edge({
    ...draftEdge,
    id: 'edge-exp6-cultivates-ba2',
    relation: 'cultivates',
    sourceId: 'experiment-comparison',
    targetId: 'ability-problem-analysis',
    source: source(
      'edge-exp6-ba2',
      'material:ds-lab-guide',
      'material-version:ds-lab-guide:v2',
      '数据结构实验指导书',
      'v2',
      '第 48 页 · 能力目标',
    ),
  }),
  edge({
    ...baseEdge,
    id: 'edge-exp5-trains-design',
    relation: 'trains',
    sourceId: 'experiment-tree',
    targetId: 'skill-algorithm-design',
    source: source(
      'edge-exp5-skill-design',
      'material:ds-lab-guide',
      'material-version:ds-lab-guide:v2',
      '数据结构实验指导书',
      'v2',
      '第 42 页 · 实验任务',
    ),
  }),
  edge({
    ...baseEdge,
    id: 'edge-exp5-trains-performance',
    relation: 'trains',
    sourceId: 'experiment-tree',
    targetId: 'skill-performance-analysis',
    source: source(
      'edge-exp5-skill-performance',
      'material:ds-lab-guide',
      'material-version:ds-lab-guide:v2',
      '数据结构实验指导书',
      'v2',
      '第 44 页 · 分析要求',
    ),
  }),
  edge({
    ...draftEdge,
    id: 'edge-exp6-trains-performance',
    relation: 'trains',
    sourceId: 'experiment-comparison',
    targetId: 'skill-performance-analysis',
    source: source(
      'edge-exp6-skill-performance',
      'material:ds-lab-guide',
      'material-version:ds-lab-guide:v2',
      '数据结构实验指导书',
      'v2',
      '第 49 页 · 实验任务',
    ),
  }),
  edge({
    ...baseEdge,
    id: 'edge-exp5-covers-tree',
    relation: 'covers',
    sourceId: 'experiment-tree',
    targetId: 'knowledge-tree-traversal',
    source: source(
      'edge-exp5-knowledge-tree',
      'material:ds-lab-guide',
      'material-version:ds-lab-guide:v2',
      '数据结构实验指导书',
      'v2',
      '第 41 页 · 预备知识',
    ),
  }),
  edge({
    ...baseEdge,
    id: 'edge-exp5-covers-complexity',
    relation: 'covers',
    sourceId: 'experiment-tree',
    targetId: 'knowledge-complexity',
    source: source(
      'edge-exp5-knowledge-complexity',
      'material:ds-lab-guide',
      'material-version:ds-lab-guide:v2',
      '数据结构实验指导书',
      'v2',
      '第 44 页 · 分析要求',
    ),
  }),
  edge({
    ...draftEdge,
    id: 'edge-exp6-covers-complexity',
    relation: 'covers',
    sourceId: 'experiment-comparison',
    targetId: 'knowledge-complexity',
    source: source(
      'edge-exp6-knowledge-complexity',
      'material:ds-lab-guide',
      'material-version:ds-lab-guide:v2',
      '数据结构实验指导书',
      'v2',
      '第 48 页 · 预备知识',
    ),
  }),
  edge({
    ...draftEdge,
    id: 'edge-exp6-uses-performance-resource',
    relation: 'uses',
    sourceId: 'experiment-comparison',
    targetId: 'resource-performance-notebook',
    source: source(
      'edge-exp6-resource',
      'material:ds-lab-guide',
      'material-version:ds-lab-guide:v2',
      '数据结构实验指导书',
      'v2',
      '第 49 页 · 实验环境',
    ),
  }),
  edge({
    ...baseEdge,
    id: 'edge-resource-enables-performance',
    relation: 'enables',
    sourceId: 'resource-performance-notebook',
    targetId: 'skill-performance-analysis',
    source: source(
      'edge-resource-skill-performance',
      'material:ds-resource-catalog',
      'material-version:ds-resource-catalog:v1',
      '数据结构实验教学资源目录',
      'v1',
      '资源 RES-DS-03 · 支撑技能',
    ),
  }),
  edge({
    ...baseEdge,
    id: 'edge-resource-enables-complexity',
    relation: 'enables',
    sourceId: 'resource-performance-notebook',
    targetId: 'knowledge-complexity',
    source: source(
      'edge-resource-knowledge-complexity',
      'material:ds-resource-catalog',
      'material-version:ds-resource-catalog:v1',
      '数据结构实验教学资源目录',
      'v1',
      '资源 RES-DS-03 · 支撑知识',
    ),
  }),
];

