import type { AbilityGraphNode } from '../abilityGraph';
import { prototypeSource as source } from './prototypeSource';

export const prototypeOutcomeNodes: AbilityGraphNode[] = [
  {
    id: 'graduate-outcome-2',
    nodeVersionId: 'node-version:graduate-outcome-2:v2025',
    code: 'GR-2',
    name: '问题分析',
    definition:
      '能够应用数学、自然科学和工程科学基本原理，识别、表达并分析复杂工程问题。',
    type: 'graduate-outcome',
    status: 'effective',
    owner: '专业负责人',
    version: 'v2025',
    source: source(
      'gr2-v2025',
      'material:program-2025',
      'material-version:program-2025:v1',
      '计算机科学与技术专业培养方案',
      '2025 版',
      '第 18 页 · 毕业要求 2',
    ),
  },
  {
    id: 'performance-indicator-2-1',
    nodeVersionId: 'node-version:performance-indicator-2-1:v1',
    code: 'PI-2.1',
    name: '识别并表达复杂工程问题',
    definition:
      '能够识别复杂工程问题中的关键对象、约束和相互关系，并形成清晰的问题表达。',
    type: 'performance-indicator',
    status: 'effective',
    owner: '专业负责人',
    version: 'v1.0',
    source: source(
      'pi21-v1',
      'material:indicator-matrix-2025',
      'material-version:indicator-matrix-2025:v1',
      '毕业要求可测量分解表',
      '2025 版',
      '表 2 · PI-2.1',
    ),
  },
  {
    id: 'course-data-structures',
    nodeVersionId: 'node-version:course-data-structures:v3',
    code: 'COURSE-DS',
    name: '数据结构',
    definition: '面向复杂数据组织、算法设计、实验验证与性能分析的专业基础课程。',
    type: 'course',
    status: 'effective',
    owner: '数据结构课程负责人',
    version: 'v3.0',
    source: source(
      'course-ds-v3',
      'material:ds-syllabus',
      'material-version:ds-syllabus:v3',
      '《数据结构》课程教学大纲',
      'v3',
      '封面 · 课程基本信息',
    ),
  },
  {
    id: 'course-outcome-ds-3',
    nodeVersionId: 'node-version:course-outcome-ds-3:v3',
    code: 'CO-DS-3',
    name: '树结构算法设计与分析',
    definition:
      '能够针对树结构问题设计遍历与查找算法，并用正确性和复杂度证据评价方案。',
    type: 'course-outcome',
    status: 'effective',
    owner: '数据结构课程负责人',
    version: 'v3.0',
    source: source(
      'co-ds-3-v3',
      'material:ds-syllabus',
      'material-version:ds-syllabus:v3',
      '《数据结构》课程教学大纲',
      'v3',
      '第 6 页 · 课程目标 3',
    ),
  },
  {
    id: 'course-outcome-ds-4',
    nodeVersionId: 'node-version:course-outcome-ds-4:v3',
    code: 'CO-DS-4',
    name: '算法性能比较与论证',
    definition:
      '能够设计测试数据比较算法在时间与空间方面的表现，并说明结论适用边界。',
    type: 'course-outcome',
    status: 'draft',
    owner: '数据结构课程负责人',
    version: 'v3.0',
    source: source(
      'co-ds-4-v3',
      'material:ds-syllabus',
      'material-version:ds-syllabus:v3',
      '《数据结构》课程教学大纲',
      'v3',
      '第 6 页 · 课程目标 4',
    ),
  },
  {
    id: 'ability-problem-analysis',
    nodeVersionId: 'node-version:ability-problem-analysis:v1',
    code: 'BA-2',
    name: '复杂工程问题分析',
    definition:
      '识别问题对象与约束，建立对象、约束和性能关系，并形成可验证的工程表达。',
    capability: {
      domain: '复杂工程问题分析',
      cognitiveLevel: 'analyze',
      observableBehaviors: [
        '识别问题对象与关键约束',
        '建立对象、约束与性能之间的关系',
        '用工程语言形成可验证的问题表达',
      ],
    },
    type: 'ability',
    status: 'effective',
    owner: '专业负责人',
    version: 'v1.0',
    source: source(
      'ability-ba2-v1',
      'material:capability-dictionary',
      'material-version:capability-dictionary:v1',
      '实验教学能力词典',
      'v1',
      '能力 BA-2',
    ),
  },
];

