import type { AbilityGraphEdge } from '../abilityGraph';
import {
  prototypeBaseEdge as baseEdge,
  prototypeDraftEdge as draftEdge,
  prototypeEdge as edge,
} from './prototypeEdgeFactory';
import { prototypeSource as source } from './prototypeSource';

export const prototypeOutcomeEdges: AbilityGraphEdge[] = [
  edge({
    ...baseEdge,
    id: 'edge-gr2-refines-pi21',
    relation: 'refines',
    sourceId: 'graduate-outcome-2',
    targetId: 'performance-indicator-2-1',
    source: source(
      'edge-gr2-pi21',
      'material:indicator-matrix-2025',
      'material-version:indicator-matrix-2025:v1',
      '毕业要求可测量分解表',
      '2025 版',
      '表 2 · GR-2 / PI-2.1',
    ),
  }),
  edge({
    ...baseEdge,
    id: 'edge-pi21-expects-ba2',
    relation: 'expects',
    sourceId: 'performance-indicator-2-1',
    targetId: 'ability-problem-analysis',
    source: source(
      'edge-pi21-ba2',
      'material:capability-dictionary',
      'material-version:capability-dictionary:v1',
      '实验教学能力词典',
      'v1',
      '映射 PI-2.1 / BA-2',
    ),
  }),
  edge({
    ...baseEdge,
    id: 'edge-course-defines-co3',
    relation: 'defines',
    sourceId: 'course-data-structures',
    targetId: 'course-outcome-ds-3',
    source: source(
      'edge-course-co3',
      'material:ds-syllabus',
      'material-version:ds-syllabus:v3',
      '《数据结构》课程教学大纲',
      'v3',
      '第 6 页 · 课程目标 3',
    ),
  }),
  edge({
    ...draftEdge,
    id: 'edge-course-defines-co4',
    edgeVersionId: 'edge-version:edge-course-defines-co4:v2',
    relation: 'defines',
    sourceId: 'course-data-structures',
    targetId: 'course-outcome-ds-4',
    source: source(
      'edge-course-co4-v3',
      'material:ds-syllabus',
      'material-version:ds-syllabus:v3',
      '《数据结构》课程教学大纲',
      'v3',
      '第 6 页 · 课程目标 4',
    ),
  }),
  edge({
    ...baseEdge,
    id: 'edge-exp5-belongs-course',
    relation: 'belongs-to',
    sourceId: 'experiment-tree',
    targetId: 'course-data-structures',
    source: source(
      'edge-exp5-course',
      'material:ds-lab-guide',
      'material-version:ds-lab-guide:v2',
      '数据结构实验指导书',
      'v2',
      '目录 · 实验五',
    ),
  }),
  edge({
    ...draftEdge,
    id: 'edge-exp6-belongs-course',
    relation: 'belongs-to',
    sourceId: 'experiment-comparison',
    targetId: 'course-data-structures',
    source: source(
      'edge-exp6-course',
      'material:ds-lab-guide',
      'material-version:ds-lab-guide:v2',
      '数据结构实验指导书',
      'v2',
      '目录 · 实验六',
    ),
  }),
  edge({
    ...baseEdge,
    id: 'edge-co3-supports-pi21',
    relation: 'supports',
    sourceId: 'course-outcome-ds-3',
    targetId: 'performance-indicator-2-1',
    capabilityMapping: {
      targetBehaviors: [
        '识别问题对象与关键约束',
        '用工程语言形成可验证的问题表达',
      ],
      rationale:
        '通过树结构问题建模、算法设计和正确性验证，承载对象识别与可验证表达。',
    },
    source: source(
      'edge-co3-pi21',
      'material:ds-syllabus',
      'material-version:ds-syllabus:v3',
      '《数据结构》课程教学大纲',
      'v3',
      '第 12 页 · 支撑矩阵',
    ),
  }),
  edge({
    ...draftEdge,
    id: 'edge-co4-supports-pi21',
    relation: 'supports',
    sourceId: 'course-outcome-ds-4',
    targetId: 'performance-indicator-2-1',
    capabilityMapping: {
      targetBehaviors: [
        '建立对象、约束与性能之间的关系',
        '用工程语言形成可验证的问题表达',
      ],
      rationale:
        '通过性能实验把数据规模、资源约束与算法表现建立为可验证关系。',
    },
    source: source(
      'edge-co4-pi21',
      'material:ds-syllabus',
      'material-version:ds-syllabus:v3',
      '《数据结构》课程教学大纲',
      'v3',
      '第 12 页 · 支撑矩阵',
    ),
  }),
  edge({
    ...baseEdge,
    id: 'edge-ability-composed-skill-design',
    relation: 'composed-of',
    sourceId: 'ability-problem-analysis',
    targetId: 'skill-algorithm-design',
    source: source(
      'edge-ba2-skill-design',
      'material:capability-dictionary',
      'material-version:capability-dictionary:v1',
      '实验教学能力词典',
      'v1',
      'BA-2 · 构成技能 1',
    ),
  }),
  edge({
    ...baseEdge,
    id: 'edge-ability-composed-skill-performance',
    relation: 'composed-of',
    sourceId: 'ability-problem-analysis',
    targetId: 'skill-performance-analysis',
    source: source(
      'edge-ba2-skill-performance',
      'material:capability-dictionary',
      'material-version:capability-dictionary:v1',
      '实验教学能力词典',
      'v1',
      'BA-2 · 构成技能 2',
    ),
  }),
  edge({
    ...baseEdge,
    id: 'edge-skill-design-requires-tree',
    relation: 'requires',
    sourceId: 'skill-algorithm-design',
    targetId: 'knowledge-tree-traversal',
    source: source(
      'edge-skill-design-tree',
      'material:capability-dictionary',
      'material-version:capability-dictionary:v1',
      '实验教学能力词典',
      'v1',
      'SK-DS-01 · 前置知识',
    ),
  }),
  edge({
    ...baseEdge,
    id: 'edge-skill-performance-requires-complexity',
    relation: 'requires',
    sourceId: 'skill-performance-analysis',
    targetId: 'knowledge-complexity',
    source: source(
      'edge-skill-performance-complexity',
      'material:capability-dictionary',
      'material-version:capability-dictionary:v1',
      '实验教学能力词典',
      'v1',
      'SK-DS-02 · 前置知识',
    ),
  }),
];

