import type { DiagnosticFinding } from './diagnosticFinding';

export const prototypeOnlyConsistencyFindings = [
  {
    id: 'finding-ds-experiment-name-conflict',
    title: '实验名称跨材料不一致',
    course: '数据结构与算法',
    type: 'material-conflict',
    risk: 'medium',
    sourceNode: '大纲：链表实现实验',
    relationLabel: '名称一致',
    targetNode: '指导书：链表综合实验',
    graphVersion: '图谱 v0.3',
    materialSnapshot: '2026-07-28',
    ruleSetVersion: '规则集 v2.4',
    suggestedDestination: 'M3',
    rule: {
      id: 'material-consistency',
      version: 'v1.8',
      kind: 'ai-semantic',
      rationale:
        '两个材料版本描述了相近实验内容，但实验名称与范围存在差异，需要课程负责人确认是否为同一实验。',
      basis: '材料一致性语义检查 3.2',
      runAt: '2026-07-28 10:26',
    },
    impact: {
      courseObjectives: 1,
      abilityNodes: 2,
      evaluationInputs: 1,
    },
    path: [
      { id: 'ds-objective', label: '课程目标', detail: '课程目标 3' },
      {
        id: 'ds-syllabus-experiment',
        label: '大纲实验',
        detail: '链表实现实验',
        tone: 'danger',
        brokenAfter: true,
      },
      {
        id: 'ds-guide-experiment',
        label: '指导书实验',
        detail: '链表综合实验',
        tone: 'target',
      },
      { id: 'ds-rubric', label: '评分项', detail: '算法正确性' },
    ],
    evidence: [
      {
        id: 'ds-syllabus-v3-table-5-1',
        objectName: '数据结构与算法课程教学大纲',
        objectVersion: 'v3',
        coordinate: '第 18 页 · 表 5-1',
        excerpt: '实验项目名称：链表实现实验，完成单链表的插入与删除。',
        hash: 'SHA256 83d4…b719',
      },
      {
        id: 'ds-guide-v2-section-3',
        objectName: '数据结构与算法实验指导书',
        objectVersion: 'v2',
        coordinate: '第 41 页 · 实验三',
        excerpt: '实验项目名称：链表综合实验，包含链表实现、遍历与性能比较。',
        hash: 'SHA256 8304…b719',
      },
    ],
  },
  {
    id: 'finding-mcu-weight-conflict',
    title: '评分标准与规则权重不一致',
    course: '单片机基础',
    type: 'material-conflict',
    risk: 'low',
    sourceNode: '评分表：硬件调试正确性 40%',
    relationLabel: '权重一致',
    targetNode: '评价规则：35%',
    graphVersion: '图谱 v0.3',
    materialSnapshot: '2026-07-28',
    ruleSetVersion: '规则集 v2.4',
    suggestedDestination: 'M3',
    rule: {
      id: 'rubric-weight-consistency',
      version: 'v1.6',
      kind: 'deterministic',
      rationale:
        '评分表与当前评价规则使用了不同权重，正式评价前需要确定权威版本。',
      basis: '评分权重一致性约束 3.4',
      runAt: '2026-07-28 10:26',
    },
    impact: {
      courseObjectives: 1,
      abilityNodes: 1,
      evaluationInputs: 1,
    },
    path: [
      { id: 'mcu-rubric', label: '评分表', detail: '40%' },
      {
        id: 'mcu-rule',
        label: '评价规则',
        detail: '35%',
        tone: 'danger',
        brokenAfter: true,
      },
      {
        id: 'mcu-evaluation',
        label: '评价输入',
        detail: '待确认',
        tone: 'target',
      },
    ],
    evidence: [
      {
        id: 'mcu-rubric-v2',
        objectName: '单片机基础实验评分表',
        objectVersion: 'v2',
        coordinate: '第 3 页 · 权重说明',
        excerpt: '硬件调试正确性占总成绩的 40%。',
        hash: 'SHA256 8c18…2d99',
      },
    ],
  },
  {
    id: 'finding-emb-objective-wording',
    title: '同名实验目标表述不一致',
    course: '嵌入式系统原理',
    type: 'material-conflict',
    risk: 'low',
    sourceNode: '大纲：LED流水灯',
    relationLabel: '目标一致',
    targetNode: '指导书：LED流水灯',
    graphVersion: '图谱 v0.3',
    materialSnapshot: '2026-07-28',
    ruleSetVersion: '规则集 v2.4',
    suggestedDestination: 'M3',
    rule: {
      id: 'objective-semantic-consistency',
      version: 'v1.8',
      kind: 'ai-semantic',
      rationale:
        '实验名称一致，但两个材料对能力目标的表述范围不同，需要教师判断是否构成实质差异。',
      basis: '材料一致性语义检查 3.3',
      runAt: '2026-07-28 10:26',
    },
    impact: {
      courseObjectives: 1,
      abilityNodes: 2,
      evaluationInputs: 1,
    },
    path: [
      { id: 'emb-syllabus', label: '大纲目标', detail: '实现LED流水灯控制' },
      {
        id: 'emb-guide',
        label: '指导书目标',
        detail: '设计并评价FPGA控制方案',
        tone: 'danger',
        brokenAfter: true,
      },
      {
        id: 'emb-ability',
        label: '能力节点',
        detail: 'C-03-01',
        tone: 'target',
      },
    ],
    evidence: [
      {
        id: 'emb-syllabus-v2',
        objectName: '嵌入式系统原理课程教学大纲',
        objectVersion: 'v2',
        coordinate: '第 15 页 · 实验一',
        excerpt: '能够基于 Verilog HDL 实现 LED流水灯控制程序。',
        hash: 'SHA256 9f0c…0f31',
      },
      {
        id: 'emb-guide-v3',
        objectName: '嵌入式系统原理实验指导书',
        objectVersion: 'v3',
        coordinate: '第 8 页 · 实验目标',
        excerpt: '能够设计、实现并评价基于 FPGA 的 LED流水灯控制方案。',
        hash: 'SHA256 16d4…a80e',
      },
    ],
  },
] as const satisfies DiagnosticFinding[];
