export const prototypeOnlyOverviewMetrics = [
  {
    key: 'standardCoverage',
    title: '标准覆盖率',
    value: 83,
    suffix: '%',
    detail: '12 条毕业要求中 10 条有课程支撑',
    tone: 'primary' as const,
    hero: true,  // 主卡：不对称布局里放大
    progress: 83,
    progressLabel: '已覆盖',
  },
  {
    key: 'avgAttainment',
    title: '达成度均值',
    value: 0.74,
    suffix: '',
    displayValue: '74',
    displaySuffix: '%',
    detail: '6 项已评价，2 项部分达成',
    tone: 'default' as const,
    hero: false,
  },
  {
    key: 'pendingReview',
    title: '待审核候选',
    value: 27,
    suffix: '条',
    detail: '7 条为高影响 AI 推荐关系',
    tone: 'warning' as const,
    hero: false,
  },
  {
    key: 'improvementTasks',
    title: '改进任务',
    value: 5,
    suffix: '项',
    detail: '2 项进行中，1 项待复评',
    tone: 'danger' as const,
    hero: false,
  },
] as const;
