import type { TeachingResource } from './teachingResource';

export const prototypeOnlyTeachingResources: TeachingResource[] = [
  {
    id: 'resource-ds-syllabus',
    name: '《数据结构》课程教学大纲',
    fileName: '数据结构课程教学大纲-2025版.pdf',
    course: '数据结构',
    resourceType: '课程大纲',
    version: 'v3',
    versionId: 'material-version:resource-ds-syllabus:v3',
    format: 'PDF',
    status: 'ready',
    size: '2.8 MB',
    pageCount: 32,
    evidenceFragments: [
      {
        id: 'fragment-ds-syllabus-01',
        coordinate: '第 6 页 · 第 2 段',
        type: '段落',
        preview: '通过线性表、树和图的实验，使学生能够选择适当的数据结构解决实际问题。',
        hash: '7fe1…0ab4',
      },
      {
        id: 'fragment-ds-syllabus-02',
        coordinate: '第 12 页 · 表 3-2 · 第 4 行',
        type: '表格',
        preview: '实验项目：二叉树遍历与应用；对应课程目标：CO2、CO3。',
        hash: 'd204…91c6',
      },
      {
        id: 'fragment-ds-syllabus-03',
        coordinate: '第 21 页 · 第 1 段',
        type: '段落',
        preview: '实验成绩由过程表现、实验报告和综合设计三个部分构成。',
        hash: '95a8…4d1f',
      },
    ],
    sourceCoverage: 96,
    sensitivity: 'internal',
    updatedAt: '2026-07-26 16:42',
    owner: '李老师',
    hash: 'SHA256 83d4…b719',
    nextAction: '可进入 M4 识别',
    processingStages: [
      { label: '安全校验', detail: '文件头、MIME 与哈希一致', status: 'finish' },
      { label: '内容解析', detail: '32 页文本与 7 个表格已提取', status: 'finish' },
      { label: '敏感检测', detail: '未发现个人敏感信息', status: 'finish' },
      { label: '分类确认', detail: '课程与材料类型已确认', status: 'finish' },
    ],
  },
  {
    id: 'resource-ds-guide',
    name: '数据结构实验指导书',
    fileName: '数据结构实验指导书-v2.docx',
    course: '数据结构',
    resourceType: '实验指导书',
    version: 'v2',
    versionId: 'material-version:resource-ds-guide:v2',
    format: 'DOCX',
    status: 'ready',
    size: '6.4 MB',
    pageCount: 84,
    evidenceFragments: [
      {
        id: 'fragment-ds-guide-01',
        coordinate: '第 14 页 · 实验二 · 目标',
        type: '段落',
        preview: '掌握栈与队列的基本操作，并能用于表达式求值和迷宫求解。',
        hash: 'fe34…6f20',
      },
      {
        id: 'fragment-ds-guide-02',
        coordinate: '第 41 页 · 表 5-1',
        type: '表格',
        preview: '关键评分点：算法正确性 40%，复杂度分析 20%，实验报告 40%。',
        hash: 'c551…26b0',
      },
    ],
    sourceCoverage: 93,
    sensitivity: 'internal',
    updatedAt: '2026-07-25 10:18',
    owner: '李老师',
    hash: 'SHA256 6ae2…af03',
    nextAction: '可进入 M4 识别',
    processingStages: [
      { label: '安全校验', detail: '文件结构与哈希校验通过', status: 'finish' },
      { label: '内容解析', detail: '84 页文本与 15 个表格已提取', status: 'finish' },
      { label: '敏感检测', detail: '未发现个人敏感信息', status: 'finish' },
      { label: '分类确认', detail: '课程与材料类型已确认', status: 'finish' },
    ],
  },
  {
    id: 'resource-ds-rubric',
    name: '数据结构综合实验评分表',
    fileName: '综合实验评分表-2025秋.xlsx',
    course: '数据结构',
    resourceType: '评分表',
    version: 'v4',
    versionId: 'material-version:resource-ds-rubric:v4',
    format: 'XLSX',
    status: 'ready',
    size: '780 KB',
    evidenceFragments: [
      {
        id: 'fragment-ds-rubric-01',
        coordinate: '工作表“评分标准” · B3:F12',
        type: '表格',
        preview: '问题分析、数据结构选择、算法实现、测试验证和报告规范五类评分项。',
        hash: 'aa27…0dd9',
      },
    ],
    sourceCoverage: 100,
    sensitivity: 'restricted',
    updatedAt: '2026-07-24 14:05',
    owner: '王老师',
    hash: 'SHA256 21f7…d38c',
    nextAction: '核对受限访问范围',
    processingStages: [
      { label: '安全校验', detail: '工作簿结构与哈希校验通过', status: 'finish' },
      { label: '内容解析', detail: '6 个工作表与 32 个评分项已提取', status: 'finish' },
      { label: '敏感检测', detail: '含评分数据，已切换受控视图', status: 'finish' },
      { label: '分类确认', detail: '课程与材料类型已确认', status: 'finish' },
    ],
  },
  {
    id: 'resource-se-guide',
    name: '软件工程课程设计指导书',
    fileName: '软件工程课程设计指导书-v2.pdf',
    course: '软件工程',
    resourceType: '实验指导书',
    version: 'v2',
    versionId: 'material-version:resource-se-guide:v2',
    format: 'PDF',
    status: 'processing',
    size: '12.6 MB',
    pageCount: 116,
    evidenceFragments: [
      {
        id: 'fragment-se-guide-01',
        coordinate: '第 8 页 · 第 3 段',
        type: '段落',
        preview: '学生应完成需求分析、架构设计、迭代实现与测试验收。',
        hash: 'e8b2…671a',
      },
    ],
    sourceCoverage: 58,
    sensitivity: 'internal',
    updatedAt: '2026-07-28 09:34',
    owner: '赵老师',
    hash: 'SHA256 bd8e…908f',
    nextAction: '等待表格解析完成',
    processingStages: [
      { label: '安全校验', detail: '文件头、MIME 与哈希一致', status: 'finish' },
      { label: '内容解析', detail: '正在解析附录中的 18 个复杂表格', status: 'process' },
      { label: '敏感检测', detail: '等待内容解析完成', status: 'wait' },
      { label: '分类确认', detail: '等待处理完成', status: 'wait' },
    ],
  },
  {
    id: 'resource-os-rubric',
    name: '操作系统实验评分记录',
    fileName: '操作系统实验评分记录-扫描版.pdf',
    course: '操作系统',
    resourceType: '评分表',
    version: 'v1',
    versionId: 'material-version:resource-os-rubric:v1',
    format: 'PDF',
    status: 'failed',
    size: '18.2 MB',
    pageCount: 47,
    evidenceFragments: [],
    sourceCoverage: 12,
    sensitivity: 'restricted',
    updatedAt: '2026-07-28 08:12',
    owner: '周老师',
    hash: 'SHA256 71c0…02ea',
    nextAction: '重新扫描后发起解析',
    failureReason: '第 9—31 页清晰度低于 OCR 阈值，无法稳定定位评分项。',
    processingStages: [
      { label: '安全校验', detail: '文件安全校验通过', status: 'finish' },
      { label: '内容解析', detail: '23 页 OCR 质量不足，任务已停止', status: 'error' },
      { label: '敏感检测', detail: '等待重新解析', status: 'wait' },
      { label: '分类确认', detail: '等待重新解析', status: 'wait' },
    ],
  },
  {
    id: 'resource-cn-reports',
    name: '计算机网络实验报告样本',
    fileName: '计算机网络实验报告样本.pdf',
    course: '计算机网络',
    resourceType: '学生报告',
    version: 'v1',
    versionId: 'material-version:resource-cn-reports:v1',
    format: 'PDF',
    status: 'quarantined',
    size: '9.7 MB',
    pageCount: 64,
    evidenceFragments: [],
    sourceCoverage: 0,
    sensitivity: 'restricted',
    updatedAt: '2026-07-27 18:26',
    owner: '陈老师',
    hash: 'SHA256 ac53…5f11',
    nextAction: '完成脱敏后解除隔离',
    failureReason: '检测到姓名与学号字段，原文件已隔离，下游不可访问。',
    processingStages: [
      { label: '安全校验', detail: '文件安全校验通过', status: 'finish' },
      { label: '内容解析', detail: '64 页文本已提取至隔离区', status: 'finish' },
      { label: '敏感检测', detail: '发现个人敏感信息，已隔离', status: 'error' },
      { label: '分类确认', detail: '等待生成脱敏视图', status: 'wait' },
    ],
  },
  {
    id: 'resource-os-project-list',
    name: '操作系统实验项目清单',
    fileName: '操作系统实验项目清单-2025.docx',
    course: '操作系统',
    resourceType: '实验项目清单',
    version: 'v1',
    versionId: 'material-version:resource-os-project-list:v1',
    format: 'DOCX',
    status: 'awaitingClassification',
    size: '1.3 MB',
    pageCount: 9,
    evidenceFragments: [
      {
        id: 'fragment-os-list-01',
        coordinate: '第 3 页 · 表 1 · 第 2 行',
        type: '表格',
        preview: '进程调度模拟：实现 FCFS、SJF 与时间片轮转，并比较等待时间。',
        hash: '83cc…741b',
      },
    ],
    sourceCoverage: 89,
    sensitivity: 'internal',
    updatedAt: '2026-07-27 15:47',
    owner: '周老师',
    hash: 'SHA256 5ca9…176e',
    nextAction: '确认课程周期与材料类型',
    processingStages: [
      { label: '安全校验', detail: '文件结构与哈希校验通过', status: 'finish' },
      { label: '内容解析', detail: '9 页文本与 4 个表格已提取', status: 'finish' },
      { label: '敏感检测', detail: '未发现个人敏感信息', status: 'finish' },
      { label: '分类确认', detail: '课程置信度 82%，等待人工确认', status: 'process' },
    ],
  },
];
