/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/evaluations/objects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出评价对象及其展示运行摘要 */
        get: operations["list_evaluation_objects_api_v1_evaluations_objects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluations/runs/{run_id}/reference": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取评价运行的权威对象引用 */
        get: operations["get_evaluation_run_reference_api_v1_evaluations_runs__run_id__reference_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluations/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取评价运行及其确定性计算明细 */
        get: operations["get_evaluation_run_api_v1_evaluations_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluations/runs/{run_id}/preflight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取精确评价运行的结构化输入预检报告 */
        get: operations["get_evaluation_preflight_api_v1_evaluations_runs__run_id__preflight_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluations/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 基于已就绪的不可变输入快照创建试点重算运行 */
        post: operations["create_evaluation_run_api_v1_evaluations_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluations/score-import-batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 捕获不可变的本地试点汇总评分批次 */
        post: operations["create_score_import_batch_api_v1_evaluations_score_import_batches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluations/score-import-batches/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取不可变的本地试点汇总评分批次 */
        get: operations["get_score_import_batch_api_v1_evaluations_score_import_batches__batch_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluations/graph-sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取由正式图谱与评价策略共同决定的评价来源 */
        get: operations["get_graph_evaluation_sources_api_v1_evaluations_graph_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取系统状态 */
        get: operations["get_system_status_api_v1_system_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出本地教学材料 */
        get: operations["list_materials_api_v1_materials_get"];
        put?: never;
        /** 上传教学材料并进入本地处理流水线 */
        post: operations["upload_material_api_v1_materials_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/materials/{material_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取材料处理详情 */
        get: operations["get_material_api_v1_materials__material_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/materials/{material_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 重试材料解析流水线 */
        post: operations["retry_material_api_v1_materials__material_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teaching-graph/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取能力图谱权威工作区 */
        get: operations["get_workspace_api_v1_teaching_graph_workspace_get"];
        /** 初始化或保存能力图谱草稿 */
        put: operations["save_workspace_api_v1_teaching_graph_workspace_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teaching-graph/imports/course-package": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 导入结构化课程包并合入图谱草稿 */
        post: operations["import_course_package_api_v1_teaching_graph_imports_course_package_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teaching-graph/workspace/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 校验并发布不可变能力图谱快照 */
        post: operations["publish_workspace_api_v1_teaching_graph_workspace_publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teaching-graph/workspace/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 基于正式快照创建下一能力图谱修订 */
        post: operations["start_revision_api_v1_teaching_graph_workspace_revisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teaching-graph/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出能力图谱追加审计事件 */
        get: operations["list_audit_events_api_v1_teaching_graph_audit_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AbilityGraphStateContract */
        AbilityGraphStateContract: {
            /** Changereviews */
            changeReviews: components["schemas"]["GraphChangeReviewContract"][];
            /** Downstreamreferences */
            downstreamReferences: components["schemas"]["GraphDownstreamReferenceContract"][];
            /** Edges */
            edges: components["schemas"]["GraphEdgeContract"][];
            /** Impactdecisions */
            impactDecisions: components["schemas"]["GraphImpactDecisionContract"][];
            /** Nodes */
            nodes: components["schemas"]["GraphNodeContract"][];
            /** Publishedsnapshots */
            publishedSnapshots: components["schemas"]["GraphPublishedSnapshotContract"][];
            /**
             * Schemaversionid
             * @constant
             */
            schemaVersionId: "teaching-graph-schema@2";
            version: components["schemas"]["GraphVersionContract"];
        };
        /** AttainmentCalculationResponse */
        AttainmentCalculationResponse: {
            /** Blockers */
            blockers: string[];
            /** Contributions */
            contributions: components["schemas"]["AttainmentContributionResponse"][];
            /** Ready */
            ready: boolean;
            result: components["schemas"]["EvaluationResultResponse"] | null;
            /** Weighttotal */
            weightTotal: number;
        };
        /** AttainmentContributionResponse */
        AttainmentContributionResponse: {
            input: components["schemas"]["EvaluationInputResponse"];
            /** Value */
            value: number | null;
        };
        /** Body_upload_material_api_v1_materials_post */
        Body_upload_material_api_v1_materials_post: {
            /**
             * File
             * @description 教学材料原始文件
             */
            file: string;
            /**
             * Course
             * @default 待分类
             */
            course: string;
            /**
             * Resource Type
             * @default 实验项目清单
             */
            resource_type: string;
        };
        /** BoundCriterionResponse */
        BoundCriterionResponse: {
            /** Criterionid */
            criterionId: string;
            /** Label */
            label: string;
            /** Evidencename */
            evidenceName: string;
            /** Edgeversionid */
            edgeVersionId: string;
            /** Weight */
            weight: number | null;
            /** Blockers */
            blockers: string[];
        };
        /**
         * ComponentStatus
         * @enum {string}
         */
        ComponentStatus: "operational" | "configured" | "not_configured";
        /** CreateEvaluationRunRequest */
        CreateEvaluationRunRequest: {
            /** Evaluationobjectid */
            evaluationObjectId: string;
            /** Sourcerunid */
            sourceRunId: string;
        };
        /**
         * CreateScoreImportBatchRequest
         * @description 创建评分批次。
         *
         *     ``profile`` 决定使用哪一组字段：
         *
         *     - ``local-pilot-aggregate:v1``：填 ``items``（每个评分项的汇总总分）；
         *     - ``local-pilot-per-student:v1``：填 ``studentItems``、``missingScorePolicy``
         *       和 ``scoreRateScale``（逐生原始分，由服务端派生汇总值）。
         *
         *     逐生口径把缺失值处理和舍入时机从表格里搬进服务端，并纳入内容摘要，
         *     因此汇总值可以被复核者从原始分重新推导。
         */
        CreateScoreImportBatchRequest: {
            /** Evaluationobjectid */
            evaluationObjectId: string;
            /** Baserunid */
            baseRunId: string;
            /**
             * Profile
             * @enum {string}
             */
            profile: "local-pilot-aggregate:v1" | "local-pilot-per-student:v1";
            /** Items */
            items?: components["schemas"]["ScoreImportCandidateItemRequest"][] | null;
            /** Studentitems */
            studentItems?: components["schemas"]["PerStudentScoreItemRequest"][] | null;
            /** Missingscorepolicy */
            missingScorePolicy?: ("exclude" | "zero" | "block") | null;
            /** Scoreratescale */
            scoreRateScale?: number | null;
        };
        /** CreateScoreImportBatchResponse */
        CreateScoreImportBatchResponse: {
            /** Idempotentreplay */
            idempotentReplay: boolean;
            batch: components["schemas"]["ScoreImportBatchResponse"];
        };
        /** EvaluationEvidenceReferenceResponse */
        EvaluationEvidenceReferenceResponse: {
            /** Coordinate */
            coordinate: string;
            /** Hash */
            hash: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Version */
            version: string;
        };
        /** EvaluationInputResponse */
        EvaluationInputResponse: {
            /** Evidencename */
            evidenceName: string;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Scorerate */
            scoreRate?: number | null;
            /** Weight */
            weight: number;
        };
        /** EvaluationInputSnapshotResponse */
        EvaluationInputSnapshotResponse: {
            /** Createdat */
            createdAt: string;
            /** Hash */
            hash: string;
        };
        /** EvaluationObjectIdentityResponse */
        EvaluationObjectIdentityResponse: {
            /** Evaluationobjectid */
            evaluationObjectId: string;
            /** Course */
            course: string;
            /** Objectivecode */
            objectiveCode: string;
            /** Objectivename */
            objectiveName: string;
            /** Abilitycode */
            abilityCode: string;
            /** Abilityname */
            abilityName: string;
        };
        /** EvaluationObjectListResponse */
        EvaluationObjectListResponse: {
            /** Items */
            items: components["schemas"]["EvaluationObjectSummaryResponse"][];
            /** Total */
            total: number;
        };
        /** EvaluationObjectSummaryResponse */
        EvaluationObjectSummaryResponse: {
            /** Evaluationobjectid */
            evaluationObjectId: string;
            /** Course */
            course: string;
            /** Objectivecode */
            objectiveCode: string;
            /** Objectivename */
            objectiveName: string;
            /** Abilitycode */
            abilityCode: string;
            /** Abilityname */
            abilityName: string;
            /** Presentedrunid */
            presentedRunId: string;
            /**
             * Readinessstatus
             * @enum {string}
             */
            readinessStatus: "ready" | "blocked";
            /**
             * Approvalstatus
             * @enum {string}
             */
            approvalStatus: "not_submitted" | "pending" | "approved" | "rejected";
            result: components["schemas"]["EvaluationResultResponse"] | null;
        };
        /** EvaluationPreflightCheckResponse */
        EvaluationPreflightCheckResponse: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Detail */
            detail: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pass" | "blocked";
            /**
             * Owner
             * @enum {string}
             */
            owner: "score_input" | "ability_graph" | "evaluation_policy" | "evaluation_owner";
            /**
             * Action
             * @enum {string}
             */
            action: "none" | "prepare_score_data" | "repair_graph_relation" | "review_evaluation_policy" | "inspect_input_snapshot";
        };
        /** EvaluationPreflightMissingInputResponse */
        EvaluationPreflightMissingInputResponse: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Evidencename */
            evidenceName: string;
        };
        /** EvaluationPreflightResponse */
        EvaluationPreflightResponse: {
            /**
             * Scope
             * @default pilot_snapshot
             * @constant
             */
            scope: "pilot_snapshot";
            /**
             * Reportversion
             * @constant
             */
            reportVersion: "evaluation-preflight:v1";
            /** Runid */
            runId: string;
            /** Evaluationobjectid */
            evaluationObjectId: string;
            /** Inputsnapshothash */
            inputSnapshotHash: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "blocked";
            /** Blockers */
            blockers: string[];
            /** Checks */
            checks: components["schemas"]["EvaluationPreflightCheckResponse"][];
            /** Missinginputs */
            missingInputs: components["schemas"]["EvaluationPreflightMissingInputResponse"][];
            /** Passedcheckcount */
            passedCheckCount: number;
            /** Blockedcheckcount */
            blockedCheckCount: number;
            /** Reporthash */
            reportHash: string;
        };
        /** EvaluationReadinessCheckResponse */
        EvaluationReadinessCheckResponse: {
            /** Detail */
            detail: string;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pass" | "blocked";
        };
        /** EvaluationResultResponse */
        EvaluationResultResponse: {
            /** Score */
            score: number;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "achieved" | "not_achieved";
        };
        /** EvaluationRunCreationErrorDetail */
        EvaluationRunCreationErrorDetail: {
            /**
             * Code
             * @enum {string}
             */
            code: "evaluation_object_not_found" | "evaluation_source_run_not_found" | "evaluation_source_run_mismatch" | "evaluation_source_run_not_ready" | "evaluation_run_idempotency_conflict";
            /** Message */
            message: string;
            /** Evaluationobjectid */
            evaluationObjectId?: string | null;
            /** Sourcerunid */
            sourceRunId?: string | null;
            /** Blockers */
            blockers?: string[] | null;
        };
        /** EvaluationRunCreationErrorResponse */
        EvaluationRunCreationErrorResponse: {
            detail: components["schemas"]["EvaluationRunCreationErrorDetail"];
        };
        /** EvaluationRunCreationResponse */
        EvaluationRunCreationResponse: {
            /** Idempotentreplay */
            idempotentReplay: boolean;
            /** Sourcerunid */
            sourceRunId: string;
            run: components["schemas"]["EvaluationRunDetailResponse"];
        };
        /** EvaluationRunDetailResponse */
        EvaluationRunDetailResponse: {
            /** Runid */
            runId: string;
            /** Sourcerunid */
            sourceRunId?: string | null;
            evaluationObject: components["schemas"]["EvaluationObjectIdentityResponse"];
            /**
             * Approvalstatus
             * @enum {string}
             */
            approvalStatus: "not_submitted" | "pending" | "approved" | "rejected";
            /** Graphversion */
            graphVersion: string;
            /** Policyversion */
            policyVersion: string;
            /** Programversion */
            programVersion: string;
            /** Scoresnapshot */
            scoreSnapshot: string;
            /** Studentcount */
            studentCount: number;
            /** Threshold */
            threshold: number;
            inputSnapshot: components["schemas"]["EvaluationInputSnapshotResponse"];
            /** Inputs */
            inputs: components["schemas"]["EvaluationInputResponse"][];
            /** Readinesschecks */
            readinessChecks: components["schemas"]["EvaluationReadinessCheckResponse"][];
            /** Evidence */
            evidence: components["schemas"]["EvaluationEvidenceReferenceResponse"][];
            calculation: components["schemas"]["AttainmentCalculationResponse"];
        };
        /** EvaluationRunReferenceNotFoundDetail */
        EvaluationRunReferenceNotFoundDetail: {
            /**
             * Code
             * @constant
             */
            code: "evaluation_run_not_found";
            /** Message */
            message: string;
            /** Runid */
            runId: string;
        };
        /** EvaluationRunReferenceNotFoundResponse */
        EvaluationRunReferenceNotFoundResponse: {
            detail: components["schemas"]["EvaluationRunReferenceNotFoundDetail"];
        };
        /** EvaluationRunReferenceResponse */
        EvaluationRunReferenceResponse: {
            /** Runid */
            runId: string;
            /** Evaluationobjectid */
            evaluationObjectId: string;
        };
        /** EvidenceFragmentResponse */
        EvidenceFragmentResponse: {
            /** Id */
            id: string;
            /** Coordinate */
            coordinate: string;
            /**
             * Type
             * @enum {string}
             */
            type: "段落" | "表格" | "扫描页";
            /** Preview */
            preview: string;
            /** Hash */
            hash: string;
        };
        /** GraphAuditEventListResponse */
        GraphAuditEventListResponse: {
            /** Items */
            items: components["schemas"]["GraphAuditEventResponse"][];
            /** Total */
            total: number;
        };
        /** GraphAuditEventResponse */
        GraphAuditEventResponse: {
            /** Action */
            action: string;
            /** Actor */
            actor: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Graphversion */
            graphVersion: string;
            /** Id */
            id: string;
            /** Revision */
            revision: number;
            /** Summary */
            summary: string;
        };
        /** GraphCapabilityContract */
        GraphCapabilityContract: {
            /**
             * Cognitivelevel
             * @enum {string}
             */
            cognitiveLevel: "understand" | "apply" | "analyze" | "evaluate" | "create";
            /** Domain */
            domain: string;
            /** Observablebehaviors */
            observableBehaviors: string[];
        };
        /** GraphCapabilityMappingContract */
        GraphCapabilityMappingContract: {
            /** Rationale */
            rationale: string;
            /** Targetbehaviors */
            targetBehaviors: string[];
        };
        /** GraphChangeReviewContract */
        GraphChangeReviewContract: {
            /** Changeid */
            changeId: string;
            /**
             * Decidedat
             * Format: date-time
             */
            decidedAt: string;
            /** Draftversion */
            draftVersion: string;
            /** Reviewer */
            reviewer: string;
        };
        /** GraphDownstreamReferenceContract */
        GraphDownstreamReferenceContract: {
            /** Edgeids */
            edgeIds: string[];
            /** Edgeversionids */
            edgeVersionIds: string[];
            /** Graphversion */
            graphVersion: string;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /**
             * Module
             * @enum {string}
             */
            module: "M5" | "M6" | "M8";
            /** Nodeids */
            nodeIds: string[];
            /** Nodeversionids */
            nodeVersionIds: string[];
            /** Objectcode */
            objectCode: string;
            /**
             * Schemaversionid
             * @constant
             */
            schemaVersionId: "teaching-graph-schema@2";
            /**
             * Suggestedaction
             * @enum {string}
             */
            suggestedAction: "recheck" | "recalculate" | "refresh";
        };
        /** GraphEdgeContract */
        GraphEdgeContract: {
            capabilityMapping?: components["schemas"]["GraphCapabilityMappingContract"] | null;
            /** Edgeversionid */
            edgeVersionId: string;
            /** Effectivecycle */
            effectiveCycle: string;
            /** Id */
            id: string;
            /**
             * Relation
             * @enum {string}
             */
            relation: "refines" | "expects" | "defines" | "belongs-to" | "supports" | "contributes-to" | "cultivates" | "trains" | "covers" | "composed-of" | "requires" | "uses" | "enables" | "contains-task" | "contains-criterion" | "assesses";
            /**
             * Reviewstatus
             * @default pending
             * @enum {string}
             */
            reviewStatus: "approved" | "pending";
            source: components["schemas"]["GraphSourceContract"];
            /** Sourceid */
            sourceId: string;
            /** Sourcenodeversionid */
            sourceNodeVersionId: string;
            /**
             * Status
             * @default draft
             * @enum {string}
             */
            status: "effective" | "draft" | "superseded";
            /** Targetid */
            targetId: string;
            /** Targetnodeversionid */
            targetNodeVersionId: string;
        };
        /**
         * GraphEvaluationSourceResponse
         * @description 一条"课程目标 → 指标点"的评价来源。
         *
         *     ``ready`` 为假时 ``blockers`` 说明缺什么。缺正式关系回 M2，
         *     缺权重绑定回 M6 策略——两者不可互相代写。
         */
        GraphEvaluationSourceResponse: {
            /** Courseoutcomeid */
            courseOutcomeId: string;
            /** Objectivecode */
            objectiveCode: string;
            /** Objectivename */
            objectiveName: string;
            /** Coursename */
            courseName: string;
            /** Indicatorcode */
            indicatorCode: string;
            /** Indicatorname */
            indicatorName: string;
            /** Abilitycode */
            abilityCode: string;
            /** Abilityname */
            abilityName: string;
            /** Graphversion */
            graphVersion: string;
            /** Policyversion */
            policyVersion: string;
            /** Threshold */
            threshold: number;
            /** Ready */
            ready: boolean;
            /** Criteria */
            criteria: components["schemas"]["BoundCriterionResponse"][];
            /** Blockers */
            blockers: string[];
        };
        /** GraphEvaluationSourcesResponse */
        GraphEvaluationSourcesResponse: {
            /** Graphversion */
            graphVersion: string;
            /** Schemaversionid */
            schemaVersionId: string;
            /** Publishedat */
            publishedAt: string;
            /** Policyversion */
            policyVersion: string;
            /** Readycount */
            readyCount: number;
            /** Sources */
            sources: components["schemas"]["GraphEvaluationSourceResponse"][];
        };
        /** GraphImpactDecisionContract */
        GraphImpactDecisionContract: {
            /**
             * Action
             * @enum {string}
             */
            action: "recheck" | "recalculate" | "refresh";
            /**
             * Decidedat
             * Format: date-time
             */
            decidedAt: string;
            /** Draftversion */
            draftVersion: string;
            /** Referenceid */
            referenceId: string;
            /** Reviewer */
            reviewer: string;
        };
        /** GraphNodeContract */
        GraphNodeContract: {
            capability?: components["schemas"]["GraphCapabilityContract"] | null;
            /** Code */
            code: string;
            /** Definition */
            definition: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Nodeversionid */
            nodeVersionId: string;
            /** Owner */
            owner: string;
            source: components["schemas"]["GraphSourceContract"];
            /**
             * Status
             * @default draft
             * @enum {string}
             */
            status: "effective" | "draft" | "superseded";
            /**
             * Type
             * @enum {string}
             */
            type: "graduate-outcome" | "performance-indicator" | "course" | "course-outcome" | "ability" | "skill" | "knowledge" | "experiment" | "teaching-resource" | "assessment-task" | "rubric-criterion";
            /** Version */
            version: string;
        };
        /** GraphPublishedSnapshotContract */
        GraphPublishedSnapshotContract: {
            /** Edges */
            edges: components["schemas"]["GraphEdgeContract"][];
            /** Nodes */
            nodes: components["schemas"]["GraphNodeContract"][];
            /**
             * Publishedat
             * Format: date-time
             */
            publishedAt: string;
            /**
             * Schemaversionid
             * @constant
             */
            schemaVersionId: "teaching-graph-schema@2";
            /** Version */
            version: string;
        };
        /** GraphRevisionCommandRequest */
        GraphRevisionCommandRequest: {
            /** Expectedrevision */
            expectedRevision: number;
        };
        /** GraphSourceContract */
        GraphSourceContract: {
            /** Coordinate */
            coordinate: string;
            /** Evidencefragmentid */
            evidenceFragmentId: string;
            /** Material */
            material: string;
            /** Materialid */
            materialId: string;
            /** Materialversionid */
            materialVersionId: string;
            /** Sourcerefid */
            sourceRefId: string;
            /** Version */
            version: string;
        };
        /** GraphVersionContract */
        GraphVersionContract: {
            /** Baseversion */
            baseVersion?: string | null;
            /** Name */
            name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "published" | "draft";
        };
        /** GraphWorkspaceResponse */
        GraphWorkspaceResponse: {
            /** Revision */
            revision: number;
            state: components["schemas"]["AbilityGraphStateContract"];
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
            /** Updatedby */
            updatedBy: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportCoursePackageRequest */
        ImportCoursePackageRequest: {
            /**
             * Packageversion
             * @constant
             */
            packageVersion: "course-package:v1";
            /** Expectedrevision */
            expectedRevision: number;
            /** Effectivecycle */
            effectiveCycle: string;
            /** Owner */
            owner: string;
            course: components["schemas"]["PackageEntityContract"];
            /** Graduateoutcomes */
            graduateOutcomes: components["schemas"]["PackageEntityContract"][];
            /** Indicators */
            indicators: components["schemas"]["PackageIndicatorContract"][];
            /** Abilities */
            abilities: components["schemas"]["PackageAbilityContract"][];
            /** Courseoutcomes */
            courseOutcomes: components["schemas"]["PackageCourseOutcomeContract"][];
            /** Experiments */
            experiments: components["schemas"]["PackageExperimentContract"][];
            /** Assessmenttasks */
            assessmentTasks: components["schemas"]["PackageAssessmentTaskContract"][];
            /** Criteria */
            criteria: components["schemas"]["PackageCriterionContract"][];
        };
        /** MaterialListResponse */
        MaterialListResponse: {
            /** Items */
            items: components["schemas"]["MaterialResponse"][];
            /** Total */
            total: number;
        };
        /** MaterialResponse */
        MaterialResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** File Name */
            file_name: string;
            /** Course */
            course: string;
            /** Resource Type */
            resource_type: string;
            /** Format */
            format: string;
            /** Media Type */
            media_type: string;
            /** Size Bytes */
            size_bytes: number;
            /** Hash */
            hash: string;
            /**
             * Status
             * @enum {string}
             */
            status: "uploaded" | "scanning" | "processing" | "ready" | "failed" | "quarantined";
            /**
             * Sensitivity
             * @enum {string}
             */
            sensitivity: "internal" | "restricted";
            /** Owner */
            owner: string;
            /** Version */
            version: string;
            /** Version Id */
            version_id: string;
            /** Source Coverage */
            source_coverage: number;
            /** Page Count */
            page_count: number | null;
            /** Failure Reason */
            failure_reason: string | null;
            /** Next Action */
            next_action: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Processing Stages */
            processing_stages: components["schemas"]["ProcessingStageResponse"][];
            /** Evidence Fragments */
            evidence_fragments: components["schemas"]["EvidenceFragmentResponse"][];
        };
        /**
         * OverallStatus
         * @enum {string}
         */
        OverallStatus: "operational" | "needs_configuration";
        /** PackageAbilityContract */
        PackageAbilityContract: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Definition */
            definition: string;
            /** Domain */
            domain: string;
            /**
             * Cognitivelevel
             * @enum {string}
             */
            cognitiveLevel: "understand" | "apply" | "analyze" | "evaluate" | "create";
            /** Observablebehaviors */
            observableBehaviors: string[];
            source: components["schemas"]["GraphSourceContract"];
        };
        /** PackageAssessmentTaskContract */
        PackageAssessmentTaskContract: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Definition */
            definition: string;
            /** Experimentcode */
            experimentCode: string;
            source: components["schemas"]["GraphSourceContract"];
        };
        /**
         * PackageCourseOutcomeContract
         * @description 课程大纲表B + 表C：课程目标及其支撑的指标点。
         *
         *     ``rationale`` 与 ``targetBehaviors`` 是支撑关系的能力映射，
         *     行为必须取自该指标点期望的能力的可观察行为。
         */
        PackageCourseOutcomeContract: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Definition */
            definition: string;
            /** Indicatorcode */
            indicatorCode: string;
            /** Rationale */
            rationale: string;
            /** Targetbehaviors */
            targetBehaviors: string[];
            source: components["schemas"]["GraphSourceContract"];
        };
        /**
         * PackageCriterionContract
         * @description 评分标准表：评分项、所属考核任务、直接评价的能力与汇总的课程目标。
         *
         *     ``abilityCode`` 产生 ``assesses``（评价效度），``courseOutcomeCode``
         *     产生 ``contributes-to``（聚合路径）。两者独立，不可互相替代。
         *     权重不在此声明——权重属于 M6 评价策略版本。
         */
        PackageCriterionContract: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Definition */
            definition: string;
            /** Taskcode */
            taskCode: string;
            /** Courseoutcomecode */
            courseOutcomeCode: string;
            /** Abilitycode */
            abilityCode: string;
            source: components["schemas"]["GraphSourceContract"];
        };
        /** PackageEntityContract */
        PackageEntityContract: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Definition */
            definition: string;
            source: components["schemas"]["GraphSourceContract"];
        };
        /**
         * PackageExperimentContract
         * @description 实验指导书 §1 §2：实验项目及其对应课程目标与培养能力。
         */
        PackageExperimentContract: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Definition */
            definition: string;
            /** Courseoutcomecodes */
            courseOutcomeCodes: string[];
            /** Abilitycodes */
            abilityCodes: string[];
            source: components["schemas"]["GraphSourceContract"];
        };
        /** PackageIndicatorContract */
        PackageIndicatorContract: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Definition */
            definition: string;
            /** Graduateoutcomecode */
            graduateOutcomeCode: string;
            /** Abilitycodes */
            abilityCodes: string[];
            source: components["schemas"]["GraphSourceContract"];
        };
        /** PerStudentScoreItemRequest */
        PerStudentScoreItemRequest: {
            /** Inputid */
            inputId: string;
            /** Maxscore */
            maxScore: string;
            /** Entries */
            entries: components["schemas"]["StudentScoreEntryRequest"][];
        };
        /** PerStudentScoreItemResponse */
        PerStudentScoreItemResponse: {
            /** Inputid */
            inputId: string;
            /** Maxscore */
            maxScore: string;
            /** Entries */
            entries: components["schemas"]["StudentScoreEntryResponse"][];
        };
        /**
         * PerStudentSourceResponse
         * @description 逐生原始输入回读。
         *
         *     保留原始分和口径声明，使复核者能够独立重算汇总值，而不必信任服务端的推导。
         */
        PerStudentSourceResponse: {
            /**
             * Missingscorepolicy
             * @enum {string}
             */
            missingScorePolicy: "exclude" | "zero" | "block";
            /** Scoreratescale */
            scoreRateScale: number;
            /** Items */
            items: components["schemas"]["PerStudentScoreItemResponse"][];
        };
        /** ProcessingStageResponse */
        ProcessingStageResponse: {
            /** Label */
            label: string;
            /** Detail */
            detail: string;
            /**
             * Status
             * @enum {string}
             */
            status: "finish" | "process" | "wait" | "error";
        };
        /** SaveGraphDraftRequest */
        SaveGraphDraftRequest: {
            /** Expectedrevision */
            expectedRevision: number;
            state: components["schemas"]["AbilityGraphStateContract"];
        };
        /** ScoreImportBatchResponse */
        ScoreImportBatchResponse: {
            /** Batchid */
            batchId: string;
            /**
             * Scope
             * @enum {string}
             */
            scope: "local_pilot_aggregate" | "local_pilot_per_student";
            /**
             * Schemaversion
             * @constant
             */
            schemaVersion: "score-import-batch:v1";
            /**
             * Profile
             * @enum {string}
             */
            profile: "local-pilot-aggregate:v1" | "local-pilot-per-student:v1";
            /**
             * Recordgranularity
             * @enum {string}
             */
            recordGranularity: "aggregate" | "per_student";
            /**
             * Formalusable
             * @default false
             * @constant
             */
            formalUsable: false;
            /** Evaluationobjectid */
            evaluationObjectId: string;
            /** Baserunid */
            baseRunId: string;
            /** Basecontextdigest */
            baseContextDigest: string;
            /**
             * Sourcekind
             * @constant
             */
            sourceKind: "structured_json";
            /** Candidateitems */
            candidateItems: components["schemas"]["ScoreImportCandidateItemResponse"][];
            /** Records */
            records: components["schemas"]["ScoreRecordResponse"][];
            perStudentSource?: components["schemas"]["PerStudentSourceResponse"] | null;
            /** Contentdigest */
            contentDigest: string;
            /** Createdat */
            createdAt: string;
            validationReport: components["schemas"]["ScoreValidationReportResponse"];
        };
        /** ScoreImportCandidateItemRequest */
        ScoreImportCandidateItemRequest: {
            /** Inputid */
            inputId: string;
            /** Earnedpointstotal */
            earnedPointsTotal: string;
            /** Possiblepointstotal */
            possiblePointsTotal: string;
            /** Observedstudentcount */
            observedStudentCount: number;
        };
        /** ScoreImportCandidateItemResponse */
        ScoreImportCandidateItemResponse: {
            /** Inputid */
            inputId: string;
            /** Earnedpointstotal */
            earnedPointsTotal: string | null;
            /** Possiblepointstotal */
            possiblePointsTotal: string | null;
            /** Observedstudentcount */
            observedStudentCount: number | null;
        };
        /** ScoreImportErrorDetail */
        ScoreImportErrorDetail: {
            /**
             * Code
             * @enum {string}
             */
            code: "pilot_score_batch_capture_disabled" | "evaluation_object_not_found" | "score_import_base_run_not_found" | "score_import_base_run_mismatch" | "score_import_base_run_does_not_need_score_data" | "score_import_idempotency_conflict" | "score_import_batch_conflict" | "score_import_batch_not_found";
            /** Message */
            message: string;
            /** Evaluationobjectid */
            evaluationObjectId?: string | null;
            /** Baserunid */
            baseRunId?: string | null;
            /** Batchid */
            batchId?: string | null;
        };
        /** ScoreImportErrorResponse */
        ScoreImportErrorResponse: {
            detail: components["schemas"]["ScoreImportErrorDetail"];
        };
        /** ScoreRecordResponse */
        ScoreRecordResponse: {
            /** Recordid */
            recordId: string;
            /** Inputid */
            inputId: string;
            /** Earnedpointstotal */
            earnedPointsTotal: string;
            /** Possiblepointstotal */
            possiblePointsTotal: string;
            /** Observedstudentcount */
            observedStudentCount: number;
            /** Scorerate */
            scoreRate: string;
            /** Scoreratescale */
            scoreRateScale: number;
        };
        /** ScoreValidationCheckResponse */
        ScoreValidationCheckResponse: {
            /** Code */
            code: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pass" | "blocked";
            /** Affectedinputids */
            affectedInputIds: string[];
            /** Expected */
            expected: string;
            /** Observed */
            observed: string;
        };
        /** ScoreValidationReportResponse */
        ScoreValidationReportResponse: {
            /** Reportid */
            reportId: string;
            /** Reportversion */
            reportVersion: string;
            /** Validatorversion */
            validatorVersion: string;
            /**
             * Validationstatus
             * @enum {string}
             */
            validationStatus: "blocked" | "pilot_ready";
            /** Checks */
            checks: components["schemas"]["ScoreValidationCheckResponse"][];
            /** Limitations */
            limitations: string[];
            /** Reportdigest */
            reportDigest: string;
            /** Createdat */
            createdAt: string;
        };
        /**
         * StudentScoreEntryRequest
         * @description 一名学生在一个评分项上的原始分。``rawScore`` 为 null 表示缺考。
         */
        StudentScoreEntryRequest: {
            /** Studentref */
            studentRef: string;
            /** Rawscore */
            rawScore?: string | null;
        };
        /** StudentScoreEntryResponse */
        StudentScoreEntryResponse: {
            /** Studentref */
            studentRef: string;
            /** Rawscore */
            rawScore: string | null;
        };
        /** SystemComponentResponse */
        SystemComponentResponse: {
            /** Key */
            key: string;
            /** Name */
            name: string;
            status: components["schemas"]["ComponentStatus"];
            /** Detail */
            detail: string;
        };
        /** SystemStatusResponse */
        SystemStatusResponse: {
            /** Service */
            service: string;
            /** Version */
            version: string;
            /** Environment */
            environment: string;
            status: components["schemas"]["OverallStatus"];
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            /** Components */
            components: components["schemas"]["SystemComponentResponse"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_evaluation_objects_api_v1_evaluations_objects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationObjectListResponse"];
                };
            };
        };
    };
    get_evaluation_run_reference_api_v1_evaluations_runs__run_id__reference_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRunReferenceResponse"];
                };
            };
            /** @description 评价运行不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRunReferenceNotFoundResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evaluation_run_api_v1_evaluations_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRunDetailResponse"];
                };
            };
            /** @description 评价运行不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRunReferenceNotFoundResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evaluation_preflight_api_v1_evaluations_runs__run_id__preflight_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationPreflightResponse"];
                };
            };
            /** @description 评价运行不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRunReferenceNotFoundResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_evaluation_run_api_v1_evaluations_runs_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEvaluationRunRequest"];
            };
        };
        responses: {
            /** @description 试点重算运行已创建或按幂等键恢复 */
            201: {
                headers: {
                    /** @description 新运行的权威详情地址 */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRunCreationResponse"];
                };
            };
            /** @description 评价对象或来源运行不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRunCreationErrorResponse"];
                };
            };
            /** @description 来源快照不可执行或幂等键冲突 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRunCreationErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_score_import_batch_api_v1_evaluations_score_import_batches_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateScoreImportBatchRequest"];
            };
        };
        responses: {
            /** @description 试点汇总评分批次已创建或按幂等键恢复 */
            201: {
                headers: {
                    /** @description 评分批次的权威详情地址 */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateScoreImportBatchResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreImportErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreImportErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreImportErrorResponse"];
                };
            };
        };
    };
    get_score_import_batch_api_v1_evaluations_score_import_batches__batch_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreImportBatchResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreImportErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreImportErrorResponse"];
                };
            };
        };
    };
    get_graph_evaluation_sources_api_v1_evaluations_graph_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphEvaluationSourcesResponse"];
                };
            };
            /** @description 尚无已发布图谱版本或生效评价策略 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_system_status_api_v1_system_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatusResponse"];
                };
            };
        };
    };
    list_materials_api_v1_materials_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialListResponse"];
                };
            };
        };
    };
    upload_material_api_v1_materials_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_material_api_v1_materials_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_material_api_v1_materials__material_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_material_api_v1_materials__material_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workspace_api_v1_teaching_graph_workspace_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphWorkspaceResponse"];
                };
            };
        };
    };
    save_workspace_api_v1_teaching_graph_workspace_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveGraphDraftRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphWorkspaceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_course_package_api_v1_teaching_graph_imports_course_package_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportCoursePackageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphWorkspaceResponse"];
                };
            };
            /** @description 图谱工作区尚未初始化 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 修订冲突、引用不完整或与现有对象冲突 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_workspace_api_v1_teaching_graph_workspace_publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GraphRevisionCommandRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphWorkspaceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_revision_api_v1_teaching_graph_workspace_revisions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GraphRevisionCommandRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphWorkspaceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_events_api_v1_teaching_graph_audit_events_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphAuditEventListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
