/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取系统状态 */
        get: operations["get_system_status_api_v1_system_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ComponentStatus
         * @enum {string}
         */
        ComponentStatus: "operational" | "configured" | "not_configured";
        /**
         * OverallStatus
         * @enum {string}
         */
        OverallStatus: "operational" | "needs_configuration";
        /** SystemComponentResponse */
        SystemComponentResponse: {
            /** Key */
            key: string;
            /** Name */
            name: string;
            status: components["schemas"]["ComponentStatus"];
            /** Detail */
            detail: string;
        };
        /** SystemStatusResponse */
        SystemStatusResponse: {
            /** Service */
            service: string;
            /** Version */
            version: string;
            /** Environment */
            environment: string;
            status: components["schemas"]["OverallStatus"];
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            /** Components */
            components: components["schemas"]["SystemComponentResponse"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_system_status_api_v1_system_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatusResponse"];
                };
            };
        };
    };
}
