import {
  colorPrimitives,
  dimensionPrimitives,
  effectPrimitives,
  radiusPrimitives,
  typographyPrimitives,
} from './primitives';

export const appThemeTokens = {
  color: {
    transparent: colorPrimitives.transparent,
    textInverse: colorPrimitives.white,
    primary: colorPrimitives.blue500,
    primaryHover: colorPrimitives.blue200,
    primaryBorder: colorPrimitives.blue200,
    primaryText: colorPrimitives.blue600,
    primaryTextHover: colorPrimitives.blue700,
    primarySoft: colorPrimitives.blue100,
    primarySurface: colorPrimitives.blue50,
    primarySurfaceHover: colorPrimitives.slate75,
    selectionBackground: colorPrimitives.blue50,
    selectionHoverBackground: colorPrimitives.blue100,
    success: colorPrimitives.green500,
    successText: colorPrimitives.green700,
    successSoft: colorPrimitives.green50,
    successBorder: colorPrimitives.green200,
    warning: colorPrimitives.amber500,
    warningSoft: colorPrimitives.amber50,
    warningIconSoft: colorPrimitives.amber100,
    warningBorder: colorPrimitives.amber200,
    warningText: colorPrimitives.amber800,
    warningTextSecondary: colorPrimitives.amber700,
    error: colorPrimitives.red500,
    errorSoft: colorPrimitives.red50,
    info: colorPrimitives.blue500,
    layout: colorPrimitives.layoutBase,
    layoutAccent: colorPrimitives.layoutAccent,
    surface: colorPrimitives.white,
    surfaceSoft: colorPrimitives.slate25,
    surfaceSider: colorPrimitives.slate50,
    border: colorPrimitives.slate200,
    borderSoft: colorPrimitives.slate100,
    borderStrong: colorPrimitives.slate250,
    borderTable: colorPrimitives.slate150,
    text: colorPrimitives.slate900,
    textSecondary: colorPrimitives.slate600,
    textMuted: colorPrimitives.slate500,
    menuText: colorPrimitives.slate700,
    tableHeaderText: colorPrimitives.slate650,
    accentIndigo: colorPrimitives.indigo500,
    accentIndigoSoft: colorPrimitives.indigo50,
    accentPurple: colorPrimitives.purple500,
    accentPurpleSoft: colorPrimitives.purple50,
  },
  layout: {
    desktopMinWidth: dimensionPrimitives.desktopMinWidth,
    desktopTargetWidth: dimensionPrimitives.desktopTargetWidth,
    sidebarWidth: dimensionPrimitives.sidebarWidth,
    headerHeight: dimensionPrimitives.headerHeight,
    workbenchMaxWidth: dimensionPrimitives.workbenchMaxWidth,
    workbenchHeaderHeight: dimensionPrimitives.workbenchHeaderHeight,
    summaryCardHeight: dimensionPrimitives.summaryCardHeight,
    controlHeight: dimensionPrimitives.controlHeight,
  },
  radius: radiusPrimitives,
  typography: typographyPrimitives,
  effect: effectPrimitives,
} as const;
