import type { WorkItem } from './workItem';

export const prototypeOnlyWorkItems: WorkItem[] = [
  {
    key: 'material-location-1',
    module: 'M3',
    priority: 'high',
    title: '确认扫描版评分表的页码与表格坐标',
    course: '数据结构',
    type: '材料处理',
    status: 'blocked',
    owner: '张老师',
    dueAt: '今天 17:00',
    action: '补充来源定位',
  },
  {
    key: 'candidate-review-1',
    module: 'M4',
    priority: 'high',
    title: '审核实验项目与课程目标 CT-3 的候选关系',
    course: '软件工程',
    type: '候选审核',
    status: 'pending',
    owner: '李老师',
    dueAt: '今天 18:00',
    action: '审核 7 条候选',
  },
  {
    key: 'diagnostic-finding-1',
    module: 'M5',
    priority: 'high',
    title: '处理评分项未关联能力节点的图谱断点',
    course: '操作系统',
    type: '图谱诊断',
    status: 'pending',
    owner: '赵老师',
    dueAt: '明天 12:00',
    action: '处理 3 个断点',
  },
  {
    key: 'evaluation-policy-1',
    module: 'M6',
    priority: 'medium',
    title: '确认课程目标达成度的缺失数据策略',
    course: '计算机网络',
    type: '评价准备',
    status: 'blocked',
    owner: '王老师',
    dueAt: '07-31',
    action: '确认评价策略',
  },
  {
    key: 'improvement-change-1',
    module: 'M7',
    priority: 'medium',
    title: '将改进措施关联到实验指导书 v2',
    course: '软件工程',
    type: '改进复评',
    status: 'processing',
    owner: '李老师',
    dueAt: '08-02',
    action: '登记实际变更',
  },
];
